import AnimatedText from "@/component/AnimatedText";
import HireMe from "@/component/HireMe";
import Kgrid from "@/component/Kgrid";
import Layout from "@/component/Layout";
import Head from "next/head";

export default function Articles() {
  return (
    <>
      <Head>
        <title>Carlos Villegas | Proyectos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout className="pt-0">

          <AnimatedText text="¡la imaginación triunfa sobre el conocimiento!"/>
          <div className="flex justify-between items-center w-full">
            <div className="w-1/2">
              <h1>Karlos</h1>
            </div>
          </div>
          <HireMe />
          {/* <Kgrid /> */}
        </Layout>
      </main>
    </>
  );
}
