import Layout from "@/component/Layout";
import Head from "next/head";
import Image from "next/image";
import karlos2 from "../../public/images/profile/karlos_2.png";
import AnimatedText from "@/component/AnimatedText";
import Link from "next/link";
import HireMe from "@/component/HireMe";
// import Kgrid from "@/component/Kgrid";
// import Kcard from "@/component/Kcard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className="pt-0">
        <div className="flex justify-between items-center w-full">
          <div className="w-1/4 fcenter ml-20">
            <Image
              src={karlos2}
              alt="Carlos Villegas"
              className='w-full h-auto rounded-full'
              priority
              sizes="(max-width: 1200px) 50vw,
                     (max-width: 768px) 100vw,
                     33vw"
            />
          </div>
          <div className="w-1/2 flex flex-col self-center items-center">
            <AnimatedText
              text="Convertir la visión en realidad con código y diseño"
              className="!text-5xl !text-left"
            />
            <p className="my-4 text-base font-medium text-justify dark:text-light">
              Como desarrollador full-stack, me dedico a convertir ideas en aplicaciones web amigables.
              Explore mis últimos proyectos, mostrando mi experiencia en Next.js y desarrollo web.
            </p>
            <p className="my-4 text-base font-medium text-justify dark:text-light">
              Soy responsable, comprometido con las labores asignadas,
              dinámico, proactivo, con iniciativa, atención al detalle,
              buenas relaciones interpersonales y capacidad de trabajo en equipo.
            </p>
            <div className="flex items-center self-start mx-4 mt-2">
              <Link
                href="/HojaVida_CarlosUrielVillegas_MINTIC.pdf"
                target={"_blank"}
                className="boton1 ktooltip hover:dark:ring-4"
              >
                Hoja Vida
                <span className='tiptext'>Descargar pdf</span>
              </Link>
              
            </div>
          </div>
        </div>
        <HireMe />
        {/* <Kgrid/> */}
        {/* <Kcard/> */}
      </Layout>
    </>
  );
}



/*************PRUEBAS *********  */
{/* <div className='grid gap-1 items-start justify-center'>
              <div className='relative group'> 
                <div className='absolute -inset-0.5 bg-gradient-to-r from-green-800 to-green-700 rounded-lg blur'>

                </div>
                <Link href="/HojaVida_CarlosUrielVillegas_MINTIC.pdf" target={"_blank"} 
                className='relative px-6 py-3 leading-none bg-black rounded-full flex items-center divide-x divide-gray-600  hover:ring-green-500  hover:ring-4'>
                  <span className='flex items-center space-x-5'>
                      <SunIcon className='h-7 w-7 text-yellow-300 group-hover:opacity-80 transition duration-300'/>

                      <span className='text-lg font-bold pr-6 text-gray-100 group-hover:text-green-400 transition duration-200'>
                        HVpdf
                      </span>
                  </span>

                  {/* <span className='pl-6 text-yellow-400 group-hover:text-green-400 transition duration-300'>&#10038;</span> */}
              {/* </Link> */}
              {/* </div> */}

              {/* </div>  */}
              {/* <Link href="mailto:carlosurielvillegas@gmail.com" className='boton2'>Contacto</Link> */}