import Layout from "@/component/Layout";
import Head from "next/head";
// import Image from "next/image";
import AnimatedText from "@/component/AnimatedText";
import Link from "next/link";
import HireMe from "@/component/HireMe";

export default function Home() {
  const  karlos2="https://res.cloudinary.com/drxhdbob1/image/upload/v1690478306/karlos_2_g9tpa8.png"
  return (
    <>
      <Head>
        <title>Carlos's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className="pt-0">
        <div className="flex justify-between items-center w-full">
          <div className="w-1/4 fcenter ml-20">
            <img src={karlos2} width={'100%'} height={200} alt="adsd"/>
            {/* <Image
              src={karlos2}
              alt="Carlos Villegas"
              className='w-full h-auto rounded-full'
              priority
              sizes="(max-width: 1200px) 50vw,
                     (max-width: 768px) 100vw,
                     33vw"
            /> */}
          </div>
          <div className="w-1/2 flex flex-col self-center items-center">
            <AnimatedText
              text="Convertir la visión en realidad con código y diseño"
              className="!text-5xl !text-left"
            />
            <p className="my-4 text-base font-medium text-justify dark:text-light">
              Como desarrollador full-stack, me dedico a convertir ideas en aplicaciones web amigables.
              Explore mis últimos proyectos, mostrando mi experiencia en Next.js y desarrollo web.
            </p>
            <p className="my-4 text-base font-medium text-justify dark:text-light">
              Soy responsable, comprometido con las labores asignadas,
              dinámico, proactivo, con iniciativa, atención al detalle,
              buenas relaciones interpersonales y capacidad de trabajo en equipo.
            </p>
            <div className="flex items-center self-start mx-4 mt-2">
              <Link
                href="/HojaVida_CarlosUrielVillegas_MINTIC.pdf"
                target={"_blank"}
                className="boton1 ktooltip hover:dark:ring-4"
              >
                Hoja Vida
                <span className='tiptext'>Descargar pdf</span>
              </Link>
              
            </div>
          </div>
        </div>
        <HireMe />
      </Layout>
    </>
  );
}
